export const dummyChats = [
  {
    id: 1,
    name: "Alice Johnson",
    lastMessage: "Cool! Let's share with the team",
    time: "10:18 AM",
    img: "https://randomuser.me/api/portraits/women/68.jpg",
    messages: [
      { from: "Alice", text: "Hey! Did you check the new design?", time: "10:15 AM" },
      { from: "Me", text: "Yes, looks amazing 👌", time: "10:17 AM" },
      { from: "Alice", text: "Cool! Let's share with the team", time: "10:18 AM" },
      { from: "Me", text: "Sure, I’ll prepare a quick deck 📑", time: "10:19 AM" },
      { from: "Alice", text: "Awesome, send it before lunch.", time: "10:20 AM" },
      { from: "Alice", text: "Hey! Did you check the new design?", time: "10:15 AM" },
      { from: "Me", text: "Yes, looks amazing 👌", time: "10:17 AM" },
      { from: "Alice", text: "Cool! Let's share with the team", time: "10:18 AM" },
      { from: "Me", text: "Sure, I’ll prepare a quick deck 📑", time: "10:19 AM" },
      { from: "Alice", text: "Awesome, send it before lunch.", time: "10:20 AM" },
    ],
  },
  {
    id: 2,
    name: "Rahul Sharma",
    lastMessage: "Cool, I’ll push to GitHub.",
    time: "10:05 AM",
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    messages: [
      { from: "Rahul", text: "I’ll update the docs by evening.", time: "09:45 AM" },
      { from: "Me", text: "Thanks Rahul 👍", time: "09:50 AM" },
      { from: "Me", text: "Also, make sure to add screenshots.", time: "09:55 AM" },
      { from: "Rahul", text: "Good point, I’ll add them too.", time: "10:00 AM" },
      { from: "Rahul", text: "Cool, I’ll push to GitHub.", time: "10:05 AM" },
    ],
  },
  {
    id: 3,
    name: "Emily Carter",
    lastMessage: "Thanks! I’ll update the calendar invite.",
    time: "Yesterday",
    img: "https://randomuser.me/api/portraits/women/12.jpg",
    messages: [
      { from: "Emily", text: "Meeting postponed to tomorrow 🚀", time: "Yesterday 2:00 PM" },
      { from: "Me", text: "Got it, thanks!", time: "Yesterday 2:05 PM" },
      { from: "Me", text: "Is it same time?", time: "Yesterday 2:06 PM" },
      { from: "Emily", text: "Yes, 11 AM sharp.", time: "Yesterday 2:10 PM" },
      { from: "Emily", text: "Thanks! I’ll update the calendar invite.", time: "Yesterday 2:12 PM" },
    ],
  },
  {
    id: 4,
    name: "David Lee",
    lastMessage: "Will do, thanks 🙌",
    time: "Yesterday",
    img: "https://randomuser.me/api/portraits/men/44.jpg",
    messages: [
      { from: "David", text: "Got it, thanks for the update!", time: "Yesterday 4:00 PM" },
      { from: "Me", text: "Anytime, buddy!", time: "Yesterday 4:02 PM" },
      { from: "Me", text: "Don’t forget to ping Mark too.", time: "Yesterday 4:05 PM" },
      { from: "David", text: "Right, will do, thanks 🙌", time: "Yesterday 4:06 PM" },
    ],
  },
  {
    id: 5,
    name: "Sophia Patel",
    lastMessage: "Great, see you then!",
    time: "Mon",
    img: "https://randomuser.me/api/portraits/women/50.jpg",
    messages: [
      { from: "Sophia", text: "Let’s catch up on call later.", time: "Mon 11:00 AM" },
      { from: "Me", text: "Sure, just ping me 📞", time: "Mon 11:05 AM" },
      { from: "Me", text: "Evening works better for me.", time: "Mon 11:06 AM" },
      { from: "Sophia", text: "Perfect, 6 PM?", time: "Mon 11:08 AM" },
      { from: "Me", text: "Yes, that works.", time: "Mon 11:10 AM" },
      { from: "Sophia", text: "Great, see you then!", time: "Mon 11:12 AM" },
    ],
  },
  {
    id: 6,
    name: "Michael Chen",
    lastMessage: "Testing now, will share results soon.",
    time: "Sun",
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    messages: [
      { from: "Michael", text: "Deployed the update on staging 🚀", time: "Sun 3:00 PM" },
      { from: "Me", text: "Awesome, I’ll test it out!", time: "Sun 3:02 PM" },
      { from: "Me", text: "Did you include the login fix?", time: "Sun 3:03 PM" },
      { from: "Michael", text: "Yes, that’s included.", time: "Sun 3:05 PM" },
      { from: "Michael", text: "Testing now, will share results soon.", time: "Sun 3:06 PM" },
    ],
  },
  {
    id: 7,
    name: "Laura Smith",
    lastMessage: "How did you celebrate? 🎉",
    time: "Sat",
    img: "https://randomuser.me/api/portraits/women/65.jpg",
    messages: [
      { from: "Laura", text: "Happy Birthday 🥳", time: "Sat 10:00 AM" },
      { from: "Me", text: "Thank you so much! ❤️", time: "Sat 10:02 AM" },
      { from: "Laura", text: "Did you get lots of cake? 🎂", time: "Sat 10:05 AM" },
      { from: "Me", text: "Haha yes, too much 😅", time: "Sat 10:06 AM" },
      { from: "Laura", text: "How did you celebrate? 🎉", time: "Sat 10:07 AM" },
    ],
  },
  {
    id: 8,
    name: "Amit Verma",
    lastMessage: "Great, I’ll prepare the slides.",
    time: "Fri",
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    messages: [
      { from: "Amit", text: "Are we meeting tomorrow?", time: "Fri 1:00 PM" },
      { from: "Me", text: "Yes, let’s meet at 11 AM ⏰", time: "Fri 1:02 PM" },
      { from: "Amit", text: "Cool, should I prepare the slides?", time: "Fri 1:05 PM" },
      { from: "Me", text: "Yes please, focus on Q3 numbers.", time: "Fri 1:07 PM" },
      { from: "Amit", text: "Great, I’ll prepare the slides.", time: "Fri 1:08 PM" },
    ],
  },
  {
    id: 9,
    name: "Jessica Brown",
    lastMessage: "Got it, I’ll check and revert.",
    time: "Thu",
    img: "https://randomuser.me/api/portraits/women/34.jpg",
    messages: [
      { from: "Jessica", text: "Check your email 📩", time: "Thu 2:00 PM" },
      { from: "Me", text: "On it right now ✅", time: "Thu 2:02 PM" },
      { from: "Me", text: "Was the doc signed?", time: "Thu 2:05 PM" },
      { from: "Jessica", text: "Not yet, waiting for approval.", time: "Thu 2:07 PM" },
      { from: "Jessica", text: "Got it, I’ll check and revert.", time: "Thu 2:10 PM" },
    ],
  },
  {
    id: 10,
    name: "Chris Evans",
    lastMessage: "Next week works for me.",
    time: "Wed",
    img: "https://randomuser.me/api/portraits/men/56.jpg",
    messages: [
      { from: "Chris", text: "Game night was fun 🎮", time: "Wed 8:00 PM" },
      { from: "Me", text: "Totally! Let’s do it again", time: "Wed 8:02 PM" },
      { from: "Chris", text: "Maybe next Friday?", time: "Wed 8:05 PM" },
      { from: "Me", text: "Sounds good, I’ll bring snacks 🍕", time: "Wed 8:06 PM" },
      { from: "Chris", text: "Next week works for me.", time: "Wed 8:07 PM" },
    ],
  },
]
